"""Simulasyon genelinde kullanilan temel ayarlar."""

# Pencere ayarlari
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
FPS = 60

WINDOW_TITLE = "Sensör ve Aktüatör Kontrollü Mobil Robot Simülasyonu"

# Renkler (R, G, B)
WHITE = (255, 255, 255)
BLACK = (30, 30, 30)
LIGHT_GRAY = (242, 245, 247)
DARK_GRAY = (75, 82, 88)
BLUE_GRAY = (105, 130, 150)
BACKGROUND_COLOR = LIGHT_GRAY
OBSTACLE_COLOR = BLUE_GRAY
OBSTACLE_BORDER_COLOR = DARK_GRAY
WORLD_BORDER_COLOR = DARK_GRAY
ROBOT_COLOR = (52, 152, 219)
ROBOT_BORDER_COLOR = (35, 92, 125)
ROBOT_DIRECTION_COLOR = BLACK
SENSOR_CLEAR_COLOR = (46, 204, 113)
SENSOR_HIT_COLOR = (231, 76, 60)
SENSOR_POINT_COLOR = (192, 57, 43)
PANEL_BACKGROUND_COLOR = (255, 255, 255)
PANEL_BORDER_COLOR = DARK_GRAY
PANEL_TEXT_COLOR = BLACK
OBSTACLE_LABEL_COLOR = WHITE

# Dünya ayarları
INFO_PANEL_HEIGHT = 90
SIMULATION_MARGIN = 10
ACTIVE_AREA_LEFT = SIMULATION_MARGIN
ACTIVE_AREA_TOP = INFO_PANEL_HEIGHT + SIMULATION_MARGIN
ACTIVE_AREA_RIGHT = SCREEN_WIDTH - SIMULATION_MARGIN
ACTIVE_AREA_BOTTOM = SCREEN_HEIGHT - SIMULATION_MARGIN
ACTIVE_AREA_RECT = (
    ACTIVE_AREA_LEFT,
    ACTIVE_AREA_TOP,
    ACTIVE_AREA_RIGHT - ACTIVE_AREA_LEFT,
    ACTIVE_AREA_BOTTOM - ACTIVE_AREA_TOP,
)
WORLD_BORDER_THICKNESS = 3

# Robot ayarları
ROBOT_START_X = 90.0
ROBOT_START_Y = 520.0
ROBOT_START_ANGLE = 0.0
ROBOT_RADIUS = 25
ROBOT_WHEEL_BASE = 45.0
ROBOT_INITIAL_LEFT_SPEED = 60.0
ROBOT_INITIAL_RIGHT_SPEED = 60.0

# Ultrasonik sensör ayarları
SENSOR_MAX_DISTANCE = 170.0
FRONT_SENSOR_ANGLE = 0.0
LEFT_SENSOR_ANGLE = -45.0
RIGHT_SENSOR_ANGLE = 45.0

# Engelden kaçma kontrol ayarları
SAFE_DISTANCE = 75.0
CRITICAL_DISTANCE = 25.0
FORWARD_SPEED = 65.0
TURN_SPEED = 55.0
REVERSE_SPEED = 45.0
REVERSE_DURATION = 0.45
WALL_AVOID_DISTANCE = 32.0
WALL_ESCAPE_RELEASE_DISTANCE = 55.0
WALL_DETOUR_DISTANCE = 35.0
SIDE_RISK_DISTANCE = 28.0
WALL_ESCAPE_SPEED = 50.0
WALL_FINE_TURN_SPEED = 18.0
WALL_TURN_TOLERANCE = 0.03

# Bilgi paneli ayarları
PANEL_HEIGHT = 58
PANEL_MARGIN = 12
PANEL_FONT_SIZE = 18
OBSTACLE_LABEL_FONT_SIZE = 14
